# Generated by Django 4.2.1 on 2023-06-29 02:30

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Generous',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('genre_title', models.CharField(max_length=200, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='Book',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200, unique=True)),
                ('description', models.TextField()),
                ('price', models.TextField(max_length=10)),
                ('nop', models.TextField(max_length=20)),
                ('genre', models.TextField(max_length=20)),
                ('isbn', models.TextField(max_length=20)),
                ('cover_image', models.ImageField(upload_to='cover')),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='cb.generous')),
            ],
        ),
    ]
